project_id = "ldqvretuwballytbywfc"

[functions.gee-ndvi-tiles]
verify_jwt = false

[functions.gee-analytics]
verify_jwt = false

[functions.ndvi-timeseries]
verify_jwt = false

[functions.keepalive]
verify_jwt = false

[functions.crop-planning]
verify_jwt = false
